ring_dimension = 8192
crt_depth = 7
crt_bits = 51
base_bits = 10
switched_modulus = "66749594872528440074844428317377254414660287576853726950110368515168786049042820743200321306624"
d = 1
input_size = 16
level_width = 8
encoding_sigma = 1.2919e1
hardcoded_key_sigma = 1.0891e35
p_sigma = 1.2919e1
input = [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
]
