ring_dimension = 4096
crt_depth = 5
crt_bits = 51
base_bits = 20
switched_modulus = "431359146674410224742050828377557384853608161148858662676258371928064"
d = 1
input_size = 1
level_width = 1
encoding_sigma = 15.82764
hardcoded_key_sigma = 15.82764
p_sigma = 15.82764
input = [true]
