ring_dimension = 8192
crt_depth = 15
crt_bits = 51
base_bits = 10
switched_modulus = "1196016433265952743395471289404579232747034820636908945861095960009346435644613511044819251563098332468497654949232640849891377973994571931894234278844142285395445742145729750254167700500929656651776"
d = 1
input_size = 56
level_width = 8
encoding_sigma = 1.0240e84
hardcoded_key_sigma = 5.1185e157
p_sigma = 1.3400e1
input = [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
]
