ring_dimension = 8192
crt_depth = 8
crt_bits = 51
base_bits = 17
switched_modulus = "1231312693637327475383719493870493847787220285090623106028843906015580388875225172571583481869828672941030578847744"
d = 1
input_size = 1
level_width = 1
encoding_sigma = 1.3842e1
hardcoded_key_sigma = 1.5625e50
p_sigma = 1.3842e1
input = [true]
