ring_dimension = 8192
crt_depth = 6
crt_bits = 51
base_bits = 10
switched_modulus = "242833611528216133864932738352939863318882873339869761108010263461767074559589089280"
d = 1
input_size = 8
level_width = 8
encoding_sigma = 1.2057e1
hardcoded_key_sigma = 4.0616e19
p_sigma = 1.2057e1
input = [true, false, false, false, false, false, false, false]
