ring_dimension = 8192
crt_depth = 13
crt_bits = 51
base_bits = 10
switched_modulus = "1932268761508629172347675745674086451925960856430994792565974057815478440586626557282051467267170004516232120316160492525196385101597902057847589028063096899898230804840448"
d = 1
input_size = 48
level_width = 8
encoding_sigma = 1.9470e53
hardcoded_key_sigma = 1.0428e127
p_sigma = 1.2506e1
input = [
    true,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
]
